spring:
  datasource:
    url: jdbc:mysql://172.17.75.168:3306/messenger?useSSL=false&serverTimezone=UTC
    username: root
    password: zczc@8888
    driver-class-name: com.mysql.cj.jdbc.Driver

  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always  # 如果 Quartz 表已经存在，设置为 never；如果需要自动创建表，设置为 always
    properties:
      org:
        quartz:
          scheduler:
            instanceName: MyScheduler
          threadPool:
            threadCount: 10
          jobStore:
            useProperties: false
            dataSource: quartzDataSource
            tablePrefix: QRTZ_
            isClustered: true
  
  rabbitmq:
    host: rabbitmq-serverless-cn-jmp40hr7g0a.cn-hangzhou.amqp-14.vpc.mq.amqp.aliyuncs.com
    port: 5672
    username: MjpyYWJiaXRtcS1zZXJ2ZXJsZXNzLWNuLWptcDQwaHI3ZzBhOkxUQUk1dExyVWtkZnhHa0ZNYmg1OFVKdA==
    password: NTUyQ0I2NkM1ODMxRUE0RjM0NzVGNzlBNjQxN0I0MURDQTA1RDBBRjoxNzMyMjAwNjA5NjQ2
    virtual-host: /

mybatis-plus:
  configuration:
    # MyBatis 配置
    map-underscore-to-camel-case: true
  global-config:
    # 全局配置
    db-config:
      # 数据库配置
      id-type: auto