spring:
  datasource:
    url: jdbc:mysql://localhost:3307/messenger?useSSL=false&serverTimezone=UTC
    username: root
    password: zczc8888
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /

mybatis-plus:
  configuration:
    # MyBatis 配置
    map-underscore-to-camel-case: true
  global-config:
    # 全局配置
    db-config:
      # 数据库配置
      id-type: auto