spring:
  datasource:
    url: jdbc:mysql://localhost:3307/messenger?useSSL=false&serverTimezone=UTC
    username: root
    password: zczc8888
    driver-class-name: com.mysql.cj.jdbc.Driver

  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always  # 如果 Quartz 表已经存在，设置为 never；如果需要自动创建表，设置为 always
    properties:
      org:
        quartz:
          scheduler:
            instanceName: MyScheduler
          threadPool:
            threadCount: 10
          jobStore:
            useProperties: false
            dataSource: quartzDataSource
            tablePrefix: QRTZ_
            isClustered: true
  
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /

mybatis-plus:
  configuration:
    # MyBatis 配置
    map-underscore-to-camel-case: true
  global-config:
    # 全局配置
    db-config:
      # 数据库配置
      id-type: auto